apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-lqzmzikh
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-lqzmzikh:115303e2aa4f08624844d1fca77630db470a02c0@sha256:e8f8af01331ee74aaa19993c78d83b48a99d7a3d52f8b877db67b0d4c0d4d7a3
          name: container-image
